import BaseContainerWithNavbar from 'components/BaseContainerWithNavbar';
import styles from './styles.module.scss';

const TermsConditions = () => {

  return (
    <BaseContainerWithNavbar withPaddingTop={true}>
      <div className={styles.container}>
       
       <div className={styles.textContainer}>
          <h1>Terms and Conditions</h1>
          <p>Last updated: 17 Dec. 21</p>

          <h2>1. Introduction</h2>
          <p>
            These terms and conditions and the documents referred to below (the “Terms”) apply to the use of the current website (the “Website”) and its related or connected services in connection with the Alpacasino operated under this Website (hereafter referred to as “Alpacasino”,  “we” or “us”).<br /><br />
            You should carefully review these Terms as they contain important information concerning your rights and obligations concerning the use of the Website and form a binding legal agreement between you - our customer (the “Customer”), and us. By using this Website and/or accessing the service, you, whether you are a guest or a registered user with an account (“Account”), agree to be bound by these Terms, together with any amendments, which may be published from time to time. If you do not accept these Terms, you must refrain from accessing the service and using the Website.<br /><br />
            The platform providing the services is owned by Wallfair N.V, a limited liability company registered in Curacao with company registration number 159041, with its registered office at Zuikertuintjeweg Z/N (Zuikertuin Tower), Curacao (“Company”), licensed in Curaçao under the Licence no. 365/JAZ Sub-License GLH-OCCHKTW0712022021  issued by Gaming Services Provider N.V. for the provision of online games of chance.
          </p>

          <h2>2. General Terms</h2>
          <p>
            We reserve the right to revise and amend the Terms (including any documents referred to and linked to below) at any time. You should visit this page periodically to review the Terms. Amendments will be binding and effective immediately upon publication on this Website. If you object to any such changes, you must immediately stop using the service. Your continued use of the Website following such publication will indicate your agreement to be bound by the Terms as amended from time to time. Any bets placed before a change of the Terms but not settled prior to the respective changed Terms become effective will be subject to the pre-existing Terms. If the Terms will be updated, the platform will notify you and ask you to confirm your consent.
          </p>
          <p>
            <b>Term of agreement.</b> These Terms shall remain in full force and effect while you access or use the service provide on or through the Website or are a Customer or visitor of the Website. These Terms will survive the cancelation or termination of your Account for any reason.
          </p>
          <p>
            <b>Gender.</b> Words importing the singular number shall include the plural and vice versa, words importing the masculine gender shall include the feminine and neuter genders and vice versa and words importing persons shall include individuals, partnerships, associations, trusts, unincorporated organisations and corporations.
          </p>
          <p>
            <b>Waiver.</b> No waiver by us, whether by conduct or otherwise, of a breach or threatened breach by you of any provisions of these Terms shall be effective against, or binding upon, us unless made in writing and duly signed by us, and, unless otherwise provided in the written waiver, shall be limited to the specific breach waived. The failure of us to enforce at any time any provisions of these Terms shall not be construed to be a waiver of such provision or of the right of us to enforce such provision at any other time.
          </p>
          <p>
            <b>Acknowledgement.</b> By hereafter accessing or using the service, you acknowledge having read, understood and agreed to each and every paragraph of these Terms. As a result, you hereby irrevocably waive any future argument, claim, demand or proceeding to the contrary of anything contained in these Terms.
          </p>
          <p>
            <b>Language.</b> In the event of there being a discrepancy between the English language version of these Terms and any other language version, the English language version will be deemed to be the correct version and shall prevail any other language version
          </p>
          <p>
            <b>Governing Law.</b> These Terms are governed by the law in force in Curaçao; and you unconditionally and irrevocably submit the exclusive (sole) right of the courts of Curaçao jurisdiction to settle any dispute resolutions (including claims for compensation and counterclaims), that may arise because of the creation, validity, effect, interpretation or action, or legal relations established by the Terms or in any other manner arising from the Terms; and you irrevocably waive any right that it may have to object to an action being brought in those courts, or to claim that the action has been brought in an inconvenient forum, or that those courts do not have jurisdiction. Nothing in this clause shall limit the right of us to take proceedings against you in any other court of competent jurisdiction, nor shall the taking of proceedings in any one or more jurisdictions preclude the taking of proceedings in any other jurisdictions, whether concurrently or not, to the extent permitted by the law of such other jurisdiction.
          </p>
          <p>
            <b>Entire agreement.</b> These Terms constitute the entire agreement between you and us with respect to your access to and use of the Website, the platform and the service provided thereon and in connection thereto, and supersedes all other prior agreements and communications, whether oral or written with respect to the subject matter hereof.
          </p>
          <p>2.1.These Terms and any contractual relationship arising in relation with the use of the platform are governed exclusively by laws of Curacao with the courts of Curacao having exclusive jurisdiction.</p>
          <p>2.2	The Parties agree to seek an amicable settlement prior to bringing any legal action against each other. Failing this, any dispute, of any nature whatsoever regarding the commercial operation, will be brought expressly before the court with jurisdiction over the Company’s registered headquarter. </p>
          <p>2.3	If any term, clause or provision of these Terms is held unlawful, void or unenforceable, then that term, clause or provision will be severable from these Terms and will not affect the validity or enforceability of any of the remaining term, clause or provision, or any other term, clause or provision of these Terms. In  case of a clause not being valid or in the case that a regulation has not been included therein, this gap shall be replaced by a valid clause that the Parties would have agreed upon if they would have known the gap.</p>
          <p>2.4 The games offered on the platform can be played exclusively based on the use of WFAIR token credits. The WFAIR token itself is a utility token developed per ERC20-based smart contracts (“WFAIR Tokens”). Alpacasino.io is a blockchain-based platform built on Polygon chain and incorporating the usability function of an WFAIR Tokens distributed through decentralized exchanges as well as this Website. It offers a graphical user interface for visualizing and interacting with data stored in a decentralized blockchain network.</p>
          <p>2.5 The Company offers exclusively WFAIR Tokens credits as a method of payment on the platform, platform participants will therefore need to acquire the WFAIR Token prior to the participation in the games offered on the platform. After the acquisition of the WFAIR Tokens these will be credited to your Account in the form of token credits and you may participate in the games and bets offered on the platform.</p>
          <p>The acquisition of the WFAIR Token itself is regulated by the following rules:</p>
          <p>
            <ul>
              <li>the participants/traders need to be able to participate in the KYC process and familiarize themselves with the risks connected to token trading and financial operations of any kind. Any participant unable to fulfill these requirements will be immediately excluded from the platform and cannot use the services provided thereon and may be liable for all consequences of such illegal events both in terms of civil and criminal liability including damages, torts and the costs of legal representation accumulated by the Company in connection to such violation.</li>
              <li>WFAIR Tokens are not shares or securities of any type. They do not entitle you to any ownership or other interest in the Company, they are merely a means by which you may be able to utilize certain services on the platform provided by the Website that is yet to be developed. There is no guarantee that the platform will actually be developed. The WFAIR Tokens are functional utility tokens that will be designed for the use on the platform provided on the Website that is yet to be developed.</li>
            </ul>
          </p>
          <p>2.6 The Company is completely responsible for the setup, content and financial frame conditions of all games that are suggested and/or placed on the platform provided by the Website. In connection hereto, the Company does not allow any activities that may qualify as illegal, unethical, fraudulent or unfair towards any of the participating parties in any of the applicable jurisdictions, be it with regard to the verification of the results, possible outcomes or unlawful agreements with the purpose of putting other platform participants at a disadvantage. Regardless the aforesaid, this Website offers gaming which involve a high risk. To be a user of our Website you must be over 18 y.o and have a high risk experience regarding gaming.</p>
          <p>2.7 All game events are reviewable by the Company`s personnel – members of staff hereby have the ultimate discretion about the placement of the games on the platform provided by the Website and the wording that can be used for the game description.</p>
          <p>2.8 These Terms are not a solicitation for investment and do not constitute a prospectus or offering of securities of any sort or any other form of capital investment product in any jurisdiction.</p>
          <p>2.9 We recommend that you consult legal, financial, tax and other professional advisors or experts for further guidance before participating in the activities offered on the platform, you are specifically strongly advised to request independent legal advice in respect of the legality of online casino platforms and your participation in it in your jurisdiction. We are not responsible for the violation of your local laws related to online-gaming.</p>
          <p>2.10 All platform participants and users should be aware that their bets are not refundable and accept the inherent risk of a total loss of any money place in a bet. This implicit risk is associated with any gaming and betting platform and can be affected by either internal or external factors that are out of the control scope of Alpacasino. There is a risk that future operations of the platform will need approvals or licenses in all or certain jurisdiction which the Company does not hold and which have not been applied for. Finally, you as a customer, visitor and user of the services provided through the platform declare to be aware of the legal uncertainty of this type of transaction and to have conducted your own legal guidance according to the applicable law to which you are subject.</p>
          <p>2.11 As part of the Know Your Customer procedure (“KYC”), anyone who would like to participate in the platform-organized activities will have to provide the Company with the following details:</p>
          <p>
            <ul>
              <li>First and last name</li>
              <li>Date and place of birth</li>
              <li>Current address</li>
              <li>Citizenship </li>
              <li>A copy of passport or ID card.</li>
            </ul>
          </p>

          <h2>3. Your Obligations</h2>
          <p>Alpacasino.io is a gambling website, do not connect to it if you are not allowed to gamble for legal, health-related, moral, religious, or psychological reasons. By accessing the Website or creating an Account on our Website, you confirm that you are in a state of mind that allows you to gamble responsibly, make responsible decisions in physically challenging conditions, and acknowledge their consequences, as well as you being legally allowed to gamble.</p>
          <p>You acknowledge and confirm that the following statements are true and correct at all times when accessing the Website and using the service provided thereon:</p>
          <p>3.1. You are over 18, or the legal age at which gambling, or gaming activities are allowed under the law or jurisdiction that applies to you. We reserve the right to request proof of age documents from you at any time. You must not access the Website or utilize the service if you are not 18.</p>
          <p>3.2. You are of legal capacity and can enter into a binding legal agreement with us. You must not access the Website or utilize the service if you are not of legal capacity.</p>
          <p>3.3. You are aware that the right to access and use the Website and any services and/or products offered thereon, may be considered illegal in certain countries. We are not able to verify the legality of service in each and every jurisdiction, consequently, you are responsible in determining whether your accessing and using our Website is compliant with the applicable laws in your country and you warrant to us that gambling is not illegal in the territory where you reside. For various legal or commercial reasons, we do not permit Accounts to be opened or used by customers resident in certain jurisdictions, including but not limited to:</p>
          <p>Afghanistan, Albania, Algeria, American Samoa, Angola, Antigua & Barbuda, Aruba, Australia, Bahamas, Belgium, Belize, Bonaire, Botswana, Bulgaria, Burkina Faso, Central African Republic, Chad, Côte d'Ivoire, Cuba, Curacao, Cyprus, Czech Republic, Democratic People’s Republic of the Congo, Denmark, Ecuador, Eritrea, Estonia, Ethiopia, France and its territories, French Guiana, French Polynesia, Germany, Ghana, Gibraltar, Guadeloupe, Guam, Guernsey, Guinea-Bissau, Guyana, Hong Kong, Hungary, Iceland, Iran, Iraq, Ireland, Israel, Italy, Jersey, Kenya, Kuwait, Korea (North Korea), Laos, Latvia, Lebanon, Libya, Liechtenstein, Lithuania, Luxembourg, Mali, Malta, Martinique, Mauritania, Mayotte,	Mexico, Morocco, Myanmar, Namibia, Netherlands, New Guinea, Nicaragua, Niger, Pakistan, Palestine, Panama, Papua, Poland, Portugal, Reunion, Romania, Saba, Serbia, Slovakia, Somalia, Spain, Sri Lanka, St. Maarten, Statia, Sudan, Sweden, Switzerland, Syria, Taiwan, the Northern Mariana Islands, the United Kingdom, the United States and all of its territories,	the US Virgin Islands,Trinidad and Tobago, Tunisia, Turkey, U.S. Virgin Islands,  Uganda, United Arab Emirates, Venezuela, Yemen, Zimbabwe or other restricted jurisdictions that are reported by us from time to time. By using the Website you confirm you are not a resident in any of the aforementioned jurisdiction.</p>
          <p>For further information regarding the territories in which we do not provide any services please see Section 4.1.3 below.</p>
          <p>3.4 You are a resident in a jurisdiction that allows gambling. You are not a resident of any country in which the access to and/or participation in online gambling is prohibited to its residents or to any person within such country is prohibited. It is your sole responsibility to ensure that your use of the service provided on the  is legal. When attempting to open an Account or using the Website, it is the responsibility of you as a player to verify whether gambling is legal in that particular jurisdiction your residing in.</p>
          <p>3.5. You may not use a VPN, proxy or similar services or devices that mask or manipulate the identification of your real location.</p>
          <p>3.6. You are the authorized user of the payment method you use and all funds, which are on your Account and used within the services are legal.</p>
          <p>3.7. You must make all payments to us in good faith and not attempt to reverse a payment made or take any action which will cause such payment to be reversed by a third party.</p>
          <p>3.8. The games offered on the Website from the Company and third parties are games of chance, games of skill and games of risk. The Company and any third parties are not responsible for any financial losses or damages which might occur to you by participating in games of chance, games of skill and games of risk. When placing bets you may loose some or all of your money deposited to the service in accordance with these Terms and you will be fully responsible for that loss.</p>
          <p>3.9. The result of games of chance and games of risk is uncertain and that the Company and its third-party partners are not responsible or liable for games not providing your desired results. By accessing the Website and agreeing to the Terms, you confirm that you know about the possible risk of financial losses, as well as other losses, and the possibility of getting addicted when participating in games of chance and games of risk. For further information regarding financial risks and health risks and how to prevent them, please study our Responsible Gambling- Policy carefully for your own benefit. You acknowledge being responsible for all addictions or side effects that might occur when taking part in games of chance or games of risk. The Company wishes to help you to avoid any side effects, including addictions, and summarized important steps, measurements, and aids to avoid addiction and side effects from gambling in its responsible gambling policy; for your own benefit, read them carefully.</p>
          <p>3.10. When placing bets you must not use any information obtained in breach of any legislation in force in the country in which you were when the bet was placed.</p>
          <p>3.11. You are not acting on behalf of another party or for any commercial purposes, but solely on your own behalf as a private individual in your personal capacity.</p>
          <p>3.12 You participate in the games strictly in your personal non-professional capacity for recreational and entertainment reasons only.</p>
          <p>3.13 All information that you provide to Alpacasino during the term of validity of this agreement is true, complete, and correct, and that you shall immediately notify Alpacasino of any change of such information.</p>
          <p>3.14. You shall not either attempt to manipulate any market or element within the service in bad faith nor in a manner that adversely affects the integrity of the service or us. You shall not be involved in any fraudulent, collusive, fixing or other unlawful activity in relation to your or third parties’ participation in any of the games and shall not use any software-assisted methods or techniques or hardware devices for Your participation in any of the games. Alpacasino hereby reserves the right to invalidate any bet/wager in the event of such behaviour;</p>
          <p>3.15. You must generally act in good faith in relation to us, the service provided through the platform on the Website, and any other users of the services at all times and for all bets made using the service.</p>
          <p>3.16. You, or, if applicable, your employees, employers, agents, or family members, are not registered as an Affiliate in our Affiliate program.</p>
          <p>3.17. While using Alpacasino at any time you consent to provide us only true, real, and objective data on default and when We request it.</p>
          <p>3.18. You understand the volatility of the crypto market and you accept the possibility of your currency/currencies price changing while you are waiting for your withdrawal or your withdrawal is being processed by our risk department. You understand that WFAIR Token credits are not considered a legal currency or tender and as such on the Website they are treated as virtual funds with no intrinsic value.</p>
          <p>3.19 You are not allowed to transfer WFAIR Token credits from your Account to other players or to receive WFAIR Token credits from other players into your Account, or to transfer, sell and/or acquire, user Accounts.</p>
          <p>3.20. You are a mentally competent person and you do not suffer from gambling addiction. In case a person with such a problem enters the Site - the responsibility lies on their side only.</p>
          <p>3.21. You agree not to use any third-party software in any of the bets placed on Alpacasino as well as not to abuse any game/functioning bugs found on the platform.</p>
          <p>3.22 All users and/players should be courteous to each other and avoid rude or obscene comments.</p>

          <h2>4. Restricted use</h2>
          <p>4.1. You must not use the service provided on the Website:</p>
          <p>4.1.1. If you are under the age of 18 years (or below the age of majority as stipulated in the laws of the jurisdiction applicable to you) or if you are not legally able to enter into a binding legal agreement with us or you acting as an agent for, or otherwise on behalf, of a person under 18 years (or below the age of majority as stipulated in the laws of the jurisdiction applicable to you);</p>
          <p>4.1.2. If you reside in a country in which access to online gambling to its residents or to any person within such country is prohibited.</p>
          <p>4.1.3. People who live or have a permanent or temporary residency in any of the following countries are not allowed to create an Account on the Website or use the Website in any way:</p>
          <p>“Prohibited Access Areas”: Australia, Aruba, Bonaire , Belize, Cyprus, Curacao, the Netherlands, Gibraltar, Guernsey, Germany, France, Hungary, Saba, Statia, St. Maarten, the United Kingdom, French Guiana, Israel, Iran, Ethiopia, Guadeloupe, Poland,, Venezuela, Cuba, Slovakia, French Polynesia, Jersey, Liechtenstein, Luxembourg, Martinique, Reunion, Mayotte, the United States and all of its territories, including but not limited to Puerto Rico, Guam, the US Virgin Islands, the Northern Mariana Islands, American Samoa and United States outlying Islands and any other jurisdiction that the Central Government of Curacao deems online gambling illegal. This shall include all the named Nations' Territories. Residents from the Prohibited Access Areas are prohibited from opening an Account or using or accessing the services or any other services offered by the company. Residents of the above-mentioned territories are not permitted to establish an Account, use or access the company’s products and services, or any other services. Thus, these zones are completely off-limits</p>
          <p>“Partially Prohibited Areas”: We do not authorize any transactions from Turkey, Argentina, Mexico, Brazil, or Colombia until we have fulfilled the KYC and AML 1 verification. Please review our KYC-AML-Policy for more details about the KYC and AML verification. Until approved, any person residing or having a permanent presence in one of these countries is barred from participating in any promotions or transactions.</p>
          <p>We currently do not accept any transactions or purchases from the following regions because of armed conflicts or political unrest (“Restricted due to Armed Conflict or Political Unrest”):</p>
          <p>This restriction is temporary and will end as soon as the armed conflicts end and political stability returns to the region. People living or having a permanent residence in one of these nations are excluded from all services on the Website and may not access the Website in any way or create an Account on our Website. Any Account found to access the Website from a restricted area due to armed conflict or political unrest via a VPN or another method to hide his identity will be banned from the Website and all services. Any Alpacasino remaining in the Alpacasino wallet will be frozen</p>
          <p><b>“Regulated Territories”: </b></p>
          <p>We do not authorize any transactions from the following territories as we do not possess a license from the local regulators of each of the following nations: Belgium, Bulgaria, Czech Republic, Germany, Denmark, Estonia, Italy, Latvia, Lithuania, Portugal, Romania, Serbia, Sweden, Switzerland.</p>
          <p>4.1.4. When attempting to open an Account or using the Website, it is the responsibility of the player to verify whether gambling is legal in that particular jurisdiction. You warrant that in the jurisdiction of your country or the country where you are currently staying, gambling or participation in games of chance, games of risk, or games of skill is not prohibited. It is your sole responsibility to make sure such restrictions or bans do not exist in your home country or the country in which you reside. You are liable to ensure you act in accordance with the laws of your home country or the country in which you currently reside. In case of any violation of these warrants, the company reserves the right to immediately block you from accessing the services and Website, close your Account and permanently freeze all your remaining balances in your Account; any winnings and rewards will be confiscated and the remaining balance returned (subject to reasonable charges), and any returns, winnings or rewards which you have gained or accrued will be forfeited by you and may be reclaimed by us; and you will return to us on demand any such funds which have been withdrawn.</p>
          <p>4.1.5. To collect nicknames, e-mail addresses and/or other information of other customers by any means (for example, by sending spam, other types of unsolicited emails or the unauthorised framing of, or linking to, the service); </p>
          <p>4.1.6. You warrant not to use any form of VPN or other methods or program fit to hide your IP or your state of origin unless you went through full ID and address verification. In addition, the usage of a VPN is only allowed with written consent from the Company. Users or customers found to use a VPN without the Company’s consent will be excluded from all services on the Website, and all remaining funds will be frozen indefinitely. You acknowledge that you are solely responsible for all losses that might occur to you over your VPN usage without the Company‘s consent, including but not limited to financial losses and the loss of your Account on the Website. </p>
          <p>4.1.7. To disrupt or unduly affect or influence the activities of other customers or the operation of the service generally;</p>
          <p>4.1.8. To promote unsolicited commercial advertisements, affiliate links, and other forms of solicitation which may be removed from the service without notice;</p>
          <p>4.1.9. In any way which, in our reasonable opinion, could be considered as an attempt to: (i) cheat the service or another customer using the service; or (ii) collude with any other customer using the service in order to obtain a dishonest advantage;</p>
          <p>4.1.10. To scrape our odds or violate any of our Intellectual Property Rights;</p>
          <p>4.1.11. For any unlawful activity whatsoever; and/or</p>
          <p>4.1.12. Creating multiple Accounts for the purpose of collusion, fraud, service abuse and/or any kind of services manipulation is prohibited and may result in Account closure.</p>
          <p>4.2. You cannot sell or transfer your Account to third parties, nor can you acquire a player Account from a third party. If you give, sell, borrow, lend or hand over your Account or anything connected to your Account in any way to someone else, your Account will be immediately frozen. All your funds will be indefinitely frozen in your Account. Your Account is given to you for personal usage to chat with other users and to non-professionally take part in games of risk, games of chance, and games of skill. Your access to the services on the Website is granted non- exclusive and non-transferable.</p>
          <p>4.3. You may not, in any manner, transfer funds between player Accounts.</p>
          <p>4.4. We may immediately terminate your Account upon written notice to you if you use the service for unauthorised purposes. We may also take legal action against you for doing so in certain circumstances.</p>
          <p>4.5. Employees of the Company, its licensees, distributors, wholesalers, subsidiaries, advertising, promotional or other agencies, media partners, contractors, retailers and members of the immediate families of each are NOT allowed to use the service for real money without prior written consent from the Company Director or CEO. Should such activity be discovered, the Account(s) will be immediately terminated and all bonuses/winnings will be forfeited.</p>
          <p>4.6 You are obligated to pay taxes on all your earnings on the Website through any games of skill, games of risk, games of chance, or games according to the governing law of the jurisdiction you are residing in. The Company and its third-party partners cannot be held liable for your failure to pay those taxes of your local jurisdiction, disregarding if they are delayed, insufficient, or not paid at all.</p>

          <h2>5. Registration</h2>
          <p>You agree that at all times when using the service:</p>
          <p>5.1. When you open an Account on the Website, you must provide us information that must be accurate, complete, and timely. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your Account on our Website and exclusion from our services. You accept if you intentionally submit that misinformation, incorrect or incomplete information, will lead to your Account being closed immediately, and all funds and WFair Tokens credit on it will be frozen on it indefinitely</p>
          <p>We reserve the right to refuse to accept a registration application from any applicant at our sole discretion and without any obligation to communicate a specific reason.</p>
          <p>5.2. Before using the service, you must personally complete the registration form and read and accept these Terms. In order to start betting on the service or withdraw your winnings, we may require you to become a verified customer which includes passing certain checks (e.g. KYC checks). You may be required to provide a valid proof of identification and any other document as it may be deemed necessary. This includes but is not limited to, a picture ID (copy of passport, driver’s licence or national ID card) and a recent utility bill listing your name and address as proof of residence. We reserve the right to suspend wagering or restrict account options on any Account until the required information is received. This procedure is done in accordance with the applicable gaming regulation and the anti-money laundering legal requirements. Additionally, you will need to fund your Account using the payment methods set out on the payment section of our Website.</p>
          <p>5.3. You have to provide accurate contact information, including among other things, a valid email address (“Registered Email Address”), and update such information in the future to keep it accurate. It is your responsibility to keep your contact details up to date on your Account. Failure to do so may result in you failing to receive important Account related notifications and information from us, including changes we make to these Terms. Any initial or grossly negligent neglect of your obligation to inform us regarding any changes in your past or current information will result in your Account being frozen indefinitely. In addition, all your remaining funds/credits in your Account will be frozen indefinitely, and you will be excluded from all current and future services on the Website. We identify and communicate with our customers via their Registered Email Address. It is the responsibility of the Customer to maintain an active and unique email account, to provide us with the correct email address and to notify the Company immediately of any changes in their email address. Each Customer is wholly responsible for maintaining the security of his Registered Email Address to prevent the use of his Registered Email Address by any third party. Company shall not be responsible for any damages or losses deemed or alleged to have resulted from communications between Company and the Customer using the Registered Email Address. Any Customer not having an email address reachable by Company will have his Account suspended until such an address is provided to us. We will immediately suspend your Account to this effect if you intentionally provide false or inaccurate personal information. We may also take legal action against you for doing so in certain circumstances and/or contact the relevant authorities who may also take action against you.</p>
          <p>5.4. You are only allowed to have one Account with the platform provided by our Website. This includes the use of representatives, relatives, associates, affiliates, related parties, connected persons and/or third parties operating on your behalf. All duplicate player Accounts will be counted as “duplicates” and will be closed immediately. Duplicate Accounts are subject to immediate closure if it is found that you have multiple Accounts registered with us. Any winnings, bonuses, and returns that you have gained from the duplicate Account we call into question, and also, we may reclaim it. You will return to us all demanded funds, which have been withdrawn from your duplicate Account. Furthermore, players who created multiple Accounts with the sole intention of taking advantage of our bonus promotions (if any) will not be eligible to receive any winnings made with our bonuses. Furthermore, their Accounts will be blocked upon recognition without prior notice.</p>
          <p>5.5. In order to ensure your financial worthiness and to confirm your identity, we may ask you to provide us with additional personal information, such as your name and surname, or use any third-party information providers in connection hereto, if deemed necessary. Should any additional personal information be obtained via third-party sources, we will inform you about the data obtained.</p>
          <p>5.6. You must keep your Account password confidential at all times. Provided that the personal information requested has been correctly supplied, we are entitled to assume that bets, deposits and withdrawals have been made by you in your own name. We advise you to change your password on a regular basis and never disclose it to any third party. It is your responsibility to protect your password and any failure to do so shall be at your sole risk and expense. You may log out of the Account at the end of each session. If you believe any of your Account information is being misused by a third party, or your Account has been hacked into, or your password has been discovered by a third party, you must notify us immediately. You must notify us if your Registered Email Address has been hacked into, we may, however, require you to provide additional information/ documentation so that we can verify your identity. We will immediately suspend your Account once we are aware of such an incident. In the meantime you are responsible for all activity on your Account including third party access, regardless of whether or not their access was authorised by you.</p>
          <p>5.7. You must not at any time transmit any content or other information on your Account and the services provided to you  to another Customer or any other party by way of a screen capture (or other similar method), nor display any such information or content in a frame or in any other manner that is different from how it would appear if such customer or third party had typed the URL for the service into the browser line.</p>
          <p>5.8. We are under no obligation to open an Account for you and our Website sign-up page is merely an invitation to apply for the opening of an Account. It is entirely within our sole discretion whether or not to proceed with the opening of an Account for you and, should we refuse to open an Account for you, we are under no obligation to provide you with a reason for the refusal.</p>
          <p>5.9. Upon receipt of your application, we may get in touch to request further information and/ or documentation from you in order for us to comply with our regulatory and legal obligations.</p>
          <p>5.10 Users who register via mail, need to verify their Account (via mail). If it will not be done within 30 days, we will delete this Account. The Company reserves the right to change this period at any time without prior notice. </p>
          <p>Identification</p>
          <p>5.11. We comply with Curacao Laws, legal regulations, and guidance for the prevention of money laundering and terrorism financing. All suspicious transactions will be investigated. In such cases, the Company is prohibited to inform the player or third parties involved in the investigation. An exception can be details that an investigation is taking place or may be carried out or that information has been or may be transmitted to the competent authorities. In case of suspicious activity, the Company has the right to suspend, freeze, block, delete or close a player’s Account and withhold funds according to law or if it is required by the competent authorities. </p>
          <p>5.12. On the Website, all transactions are checked to prevent money laundering and other illegal activity. If you agree with the Terms, you authorize us to undertake a personal identification check, due to our requirements or requirements from the third party (including regulatory authority) to confirm your identity and contact details. In certain circumstances, we may have to contact you and ask you to provide the necessary information in order to complete the check. If you do not provide us with the required information, the Company reserves the right to freeze or close your Account until you have provided us with the requested information.</p>
          <p>5.13. If you do not confirm that you already are 18 years old, the Company has the right to freeze your Account until you prove your age. If it is proved that you are younger than 18 years old and you did some actions on the Website, the provisions of Clause 16 shall apply.</p>
          <p>5.14. If you breach these Terms, or we have a reasonable suspicion that you did so, we may with or without prior notice to you terminate your Account. In such case, all your outstanding bets will be canceled, and your Account will be closed, and we may also confiscate and recover from your Account balance the amount of the winnings awarded or paid to you and all bonuses, bonus money, and other incentives, which you shall forfeit in such case. Following this, on your request and subject to our discretion, we will return the remainder of the real money balance of your Account (if any) to you, subject to reasonable charges, regulatory obligations, and our ability to do so using the payment method we verified as belonging solely to you.</p>

          <h2>6. Your Account</h2>
          <p>6.1. Accounts can use several currencies, in this case all Account balances and transactions appear in the currency used for the respective transaction.</p>
          <p>6.2. We do not give credit for the use of the service. However, we may grant a bonus from time to time for the registration as a user of a platform as well as a referral bonus for the referral of new users to our platform. The granting of a bonus and/or a referral bonus is, however, at our sole discretion and may be cancelled and terminated at any time.</p>
          <p>6.3. We may close or suspend an Account immediately if you are not or we reasonably believe that you are not complying with these Terms, or to ensure the integrity or fairness of the service provided on the Website or if we have other reasonable grounds to do so. We may not always be able to give you prior notice. If we close or suspend your Account due to you not complying with these Terms, we may cancel and/or void any of your bets and withhold any money in your Account (including the deposit).</p>
          <p>6.4. We reserve the right to close or suspend any Account without prior notice. Unless stated otherwise herein, contractual obligations already matured will however be honoured.</p>
          <p>6.5. We reserve the right to refuse, restrict, cancel or limit any wager at any time for whatever reason, including any bet perceived to be placed in a fraudulent manner in order to circumvent our betting limits and/ or our system regulations.</p>
          <p>6.6. If any amount is mistakenly credited to your Account it remains our property and when we become aware of any such mistake, we shall notify you and the amount will be withdrawn from your Account.</p>
          <p>6.7. In general, we do not grant any credits to player. If, however, for any reason, your Account goes overdrawn, you shall be in debt to us for the amount overdrawn.</p>
          <p>6.8. You must inform us immediately as soon as you become aware of any errors with respect to your Account. In the event we deem in our sole discretion that you have been taking unfair advantage of any bonuses or have executed any other act in bad faith in relation to a bonus, promotion offered on the Website, we shall have the right to block or terminate your Account and, in such circumstances, we shall be under no obligation to refund you any funds that may be in your Account.</p>
          <p>6.9. Please remember that betting is purely for entertainment and pleasure, and you should stop as soon as it stops being fun. Absolutely do not bet anything you can’t afford to lose. If you feel that you may have lost control of your gambling, we offer a self-exclusion option. Just send a message to our customer support department using your Registered Email Address that you wish to SELF-EXCLUDE and this request will take effect within 24 hours from the moment of its receipt. In this case your Account will be disabled until your further notice, and you won’t be able to login to it.</p>
          <p>6.10. You cannot transfer, sell, or pledge your Account to another person. This prohibition includes the transfer of any assets of value of any kind, including but not limited to ownership of accounts, winnings, deposits, bets, rights and/or claims in connection with these assets, legal, commercial or otherwise. The prohibition on said transfers also includes however is not limited to the encumbrance, pledging, assigning, usufruct, trading, brokering, hypothecation and/or gifting in cooperation with a fiduciary or any other third party, company, natural or legal individual, foundation and/or association in any way shape or form</p>
          <p>6.11. Should you wish to close your Account with us, please send an email from your Registered Email Address to our customer support department via the links on the Website. . When you make a request for the Account closure, you accept the fact that your Account is not going to be ever unlocked. It is advisable to withdraw all of your funds before closing the Account.</p>

          <h2>7. Inactive Accounts</h2>
          <p>7.1. We will charge you a fee of €5 (or another currency equivalent) per calendar month (“Inactive Account Fee”) if:</p>
          <p>
            a. you have not logged into your Account or logged out from your Account, or used the service, or made any bet in any section of the service for twelve consecutive months or more (“Account Activity”); and <br/>
            b. your Account is in credit.
          </p>


          <h2>8. Deposit of Funds</h2>
          <p>
            8.1. All deposits should be made from an account or payment system or credit card that is registered in your own name, and any deposits made in any other currency will be converted using the daily exchange rate obtained from oanda.com, or at our own bank's or our payment processor’s prevailing rate of exchange following which your Account will be deposited accordingly. Note that some payment systems may apply additional currency exchange fees which will be deducted from the sum of your deposit.<br />
            8.2. Fees and charges may apply to customer deposits and withdrawals, which can be found on the Website. In most cases we absorb transaction fees for deposits to your alpacasino.io Account. You are responsible for your own bank charges that you may incur due to depositing funds with us.<br />
            8.3. Company is not a financial institution and uses a third party electronic payment processors to process credit and debit card deposits; they are not processed directly by us. If you deposit funds by either a credit card or a debit card, your Account will only be credited if we receive an approval and authorisation code from the payment issuing institution. If your card issuer gives no such authorisation, your Account will not be credited with those funds.<br />
            8.4. You agree to fully pay any and all payments and charges due to us or to payment providers in connection with your use of the Service. You further agree not to make any charge-backs or renounce or cancel or otherwise reverse any of your deposits, and in any such event you will refund and compensate us for such unpaid deposits including any expenses incurred by us in the process of collecting your deposit, and you agree that any winnings from wagers utilising those charged back funds will be forfeited. You acknowledge and agree that your player account is not a bank account and is therefore not guaranteed, insured or otherwise protected by any deposit or banking insurance system or by any other similar insurance system of any other jurisdiction, including but not limited to your local jurisdiction. Furthermore, the player account does not bear interest on any of the funds held in it.<br />
            8.5. If you decide to accept any of our promotional or bonus offer by entering a bonus code during deposit, you agree to the Terms of Bonuses and terms of each specific bonus.<br />
            8.6. Funds originating from criminal and/or illegal and/or unauthorized activities must not be deposited with us.<br />
            8.7. If you deposit using your credit card, it is recommended that you retain a copy of Transaction Records and a copy of these Terms.<br />
            8.8. Internet Gambling may be illegal in the jurisdiction in which you are located; if so, you are not authorized to use your payment card to deposit on this site. It is your responsibility to know the laws concerning online gambling in your country of domicile.
          </p>

          <h2>9. Withdrawal of Funds</h2>
          <p>
            9.1. You may withdraw any unutilized and cleared funds held in your player account by submitting a withdrawal request in accordance with our withdrawal conditions. The minimum withdrawal amount per transaction is € 10 (or equivalent in other currency) with the exception of an account closure in which case you may withdraw the full balance.<br />
            9.2. There are no withdrawal commissions if you roll over (wager) the deposit at least 1 time. Otherwise we are entitled to deduct a 8% fee with minimum sum of 4 euro (or equivalent in your account currency) in order to combat money laundering.<br />
            9.3. We reserve the right to request photo ID, address confirmation or perform additional verification procedures (request your selfie, arrange a verification call etc.) for the purpose of identity verification prior to granting any withdrawals from your Account. We also reserve our rights to perform identity verification at any time during the lifetime of your relationship with us.<br />
            9.4. All withdrawals must be made to the original debit, credit card, bank account, method of payment used to make the payment to your Account. We may, and always at our own discretion, allow you to withdraw to a payment method from which your original deposit did not originate. This will always be subject to additional security checks.<br />
            9.5. Should you wish to withdraw funds but your account is either inaccessible, dormant, locked or closed, please contact our Customer Service Department.<br />
            9.6. In cases when your balance is at least 10 times larger than the total sum of your deposits, you will be limited to € 5,000 (or currency equivalent) for withdrawal per month. In other cases the maximum withdrawal amount per month is € 10,000.<br />
            9.7. Please note that we cannot guarantee successful processing of withdrawals or refunds in the event if you breach the Restricted use policy stated in Clauses 3.3 and 4.
          </p>

          <h2>10. Payment Transactions and Processors</h2>
          <p>
            10.1. You are fully responsible for paying all monies owed to us. You must make all payments to us in good faith and not attempt to reverse a payment made or take any action which will cause such payment to be reversed by a third party in order to avoid a liability legitimately incurred. You will reimburse us for any charge-backs, denial or reversal of payment you make and any loss suffered by us as a consequence thereof. We reserve the right to also impose an administration fee of €50, or currency equivalent per charge-back, denial or reversal of payment you make.<br />
            10.2. We reserve the right to use third party electronic payment processors and or merchant banks to process payments made by you and you agree to be bound by their terms and conditions providing they are made aware to you and those terms do not conflict with these Terms.<br />
            10.3. All transactions made on our site might be checked to prevent money laundering or terrorism financing activity. Suspicious transactions will be reported to the relevant authority.<br />
          </p>

          <h2>11. Errors</h2>
          <p>
            11.1. In the event of an error or malfunction of our system or processes, all bets are rendered void. You are under an obligation to inform us immediately as soon as you become aware of any error with the Service. In the event of communication or system errors or bugs or viruses occurring in connection with the Service and/or payments made to you as a result of a defect or error in the Service, we will not be liable to you or to any third party for any direct or indirect costs, expenses, losses or claims arising or resulting from such errors, and we reserve the right to void all games/bets in question and take any other action to correct such errors.<br />
            11.2. We make every effort to ensure that we do not make errors in posting bookmaker lines. However, if as a result of human error or system problems a bet is accepted at an odd that is: materially different from those available in the general market at the time the bet was made; or clearly incorrect given the chance of the event occurring at the time the bet was made then we reserve the right to cancel or void that wager, or to cancel or void a wager made after an event has started.<br />
            11.3. We have the right to recover from you any amount overpaid and to adjust your Account to rectify any mistake. An example of such a mistake might be where a price is incorrect or where we enter a result of an event incorrectly. If there are insufficient funds in your Account, we may demand that you pay us the relevant outstanding amount relating to any erroneous bets or wagers. Accordingly, we reserve the right to cancel, reduce or delete any pending plays, whether placed with funds resulting from the error or not.
          </p>

          <h2>12. Rules of Play, refunds and cancellations</h2>
          <p>
            12.1. The winner of an event will be determined on the date of the event's settlement, and we will not recognize protested or overturned decisions for wagering purposes.<br />
            12.2. All results posted shall be final after 72 hours and no queries will be entertained after that period of time. Within 72 hours after results are posted, we will only reset/correct the results due to human error, system error or mistakes made by the referring results source.<br />
            12.3. If a match result is overturned for any reason by the governing body of the match within the payout period then all money will be refunded.<br />
            12.4. If a draw occurs in a game where a draw option is offered all stakes on a team win or lose will be lost. If a draw option is not offered then everyone receives a refund in the outcome of a draw on the match. And if a draw option has not been made available, then extra time will count, if played.<br />
            12.5. If a result cannot be validated by us, for instance if the feed broadcasting the event is interrupted (and cannot be verified by another source) then at our election, the wagers on that event will be deemed invalid and wagers refunded.<br />
            12.6. Minimum and maximum wager amounts on all events will be determined by us and are subject to change without prior written notice. We also reserve the right to adjust limits on individual Accounts as well.<br />
            12.7. Customers are solely responsible for their own Account transactions. Once a transaction is complete, it cannot be changed. We do not take responsibility for missing or duplicate wagers made by the Customer and will not entertain discrepancy requests because a play is missing or duplicated. Customers may review their transactions in the My Account section of the site after each session to ensure all requested wagers were accepted.<br />
            12.8. A matchup will have action as long as the two teams are correct, and regardless of the League header in which it is placed on our Website.<br />
            12.9. The start dates and times displayed on the Website for eSport matches are an indication only and are not guaranteed to be correct. If a match is suspended or postponed, and not resumed within 72 hours from the actual scheduled start time, the match will have no action and wagers will be refunded. The exception being any wager on whether a team/player advances in a tournament, or wins the tournament, will have action regardless of a suspended or postponed match.<br />
            12.10. If an event is posted by us with an incorrect date, all wagers have action based on the date announced by the governing body.<br />
            12.11. If a team is using stand-ins, the result is still valid as it was the team's choice to use the stand-ins.<br />
            12.12. Company reserves the right to remove events, markets and any other products from the Website.<br />
            12.13. In-depth explanation of our sports betting rules is on the separate page: SPORTS BETTING RULES
          </p>

          <h2>13. Communications and Notices</h2>
          <p>
            13.1. All communications and notices to be given under these Terms by you to us shall be sent using a Customer Support form on the Website.<br />
            13.2. All communications and notices to be given under these Terms by us to you shall, unless otherwise specified in these Terms, be either posted on the Website and/or sent to the Registered Email Address we hold on our system for the relevant Customer. The method of such communication shall be in our sole and exclusive discretion.<br />
            13.3. All communications and notices to be given under these Terms by either you or us shall be in writing in the English language and must be given to and from the Registered Email Address in your Account.<br />
            13.4. From time to time, we may contact you by email for the purpose of offering you information about betting, unique promotional offerings, and other information from alpacasino.io. You agree to receive such emails when you agree to these Terms when registering at the Website. You can choose to opt out of receiving such promotional offerings from us at any time by submitting a request to the Customer Support.
          </p>

          <h2>14. Communications and Notices</h2>
          <p>
            We cannot be held liable for any failure or delay in providing the Service due to an event of Force Majeure which could reasonably be considered to be outside our control despite our execution of reasonable preventative measures such as: an act of God; trade or labour dispute; power cut; act, failure or omission of any government or authority; obstruction or failure of telecommunication services; or any other delay or failure caused by a third party, and we will not be liable for any resulting loss or damage that you may suffer. In such an event, we reserve the right to cancel or suspend the Service without incurring any liability.
          </p>

          <h2>15. Liability</h2>
          <p>
            15.1. TO THE EXTENT PERMITTED BY APPLICABLE LAW, WE WILL NOT COMPENSATE YOU FOR ANY REASONABLY FORESEEABLE LOSS OR DAMAGE (EITHER DIRECT OR INDIRECT) YOU MAY SUFFER IF WE FAIL TO CARRY OUT OUR OBLIGATIONS UNDER THESE TERMS UNLESS WE BREACH ANY DUTIES IMPOSED ON US BY LAW (INCLUDING IF WE CAUSE DEATH OR PERSONAL INJURY BY OUR NEGLIGENCE) IN WHICH CASE WE SHALL NOT BE LIABLE TO YOU IF THAT FAILURE IS ATTRIBUTED TO: (I) YOUR OWN FAULT; (II) A THIRD PARTY UNCONNECTED WITH OUR PERFORMANCE OF THESE TERMS (FOR INSTANCE PROBLEMS DUE TO COMMUNICATIONS NETWORK PERFORMANCE, CONGESTION, AND CONNECTIVITY OR THE PERFORMANCE OF YOUR COMPUTER EQUIPMENT); OR (III) ANY OTHER EVENTS WHICH NEITHER WE NOR OUR SUPPLIERS COULD HAVE FORESEEN OR FORESTALLED EVEN IF WE OR THEY HAD TAKEN REASONABLE CARE. AS THIS SERVICE IS FOR CONSUMER USE ONLY WE WILL NOT BE LIABLE FOR ANY BUSINESS LOSSES OF ANY KIND.<br />
            15.2. IN THE EVENT THAT WE ARE HELD LIABLE FOR ANY EVENT UNDER THESE TERMS, OUR TOTAL AGGREGATE LIABILITY TO YOU UNDER OR IN CONNECTION WITH THESE TERMS SHALL NOT EXCEED (A) THE VALUE OF THE BETS AND OR WAGERS YOU PLACED VIA YOUR ACCOUNT IN RESPECT OF THE RELEVANT BET/WAGER OR PRODUCT THAT GAVE RISE TO THE RELEVANT LIABILITY, OR (B) EUR €500 IN AGGREGATE, WHICHEVER IS LOWER.<br />
            15.3. WE STRONGLY RECOMMEND THAT YOU (I) TAKE CARE TO VERIFY THE SUITABILITY AND COMPATIBILITY OF THE SERVICE WITH YOUR OWN COMPUTER EQUIPMENT PRIOR TO USE; AND (II) TAKE REASONABLE PRECAUTIONS TO PROTECT YOURSELF AGAINST HARMFUL PROGRAMS OR DEVICES INCLUDING THROUGH INSTALLATION OF ANTI-VIRUS SOFTWARE.
          </p>

          <h2>16. Gambling By Those Under Age</h2>
          <p>
            16.1. If we suspect that you are or receive notification that you are currently under 18 years or were under 18 years (or below the age of majority as stipulated in the laws of the jurisdiction applicable to you) when you placed any bets through the Service your Account will be suspended (locked) to prevent you placing any further bets or making any withdrawals from your Account. We will then investigate the matter, including whether you have been betting as an agent for, or otherwise on behalf, of a person under 18 years (or below the age of majority as stipulated in the laws of the jurisdiction applicable to you). If having found that you: (a) are currently; (b) were under 18 years or below the majority age which applies to you at the relevant time; or (c) have been betting as an agent for or at the behest of a person under 18 years or below the majority age which applies:<br />
            <ul>
              <li>all winnings currently or due to be credited to your Account will be retained;</li>
              <li>all winnings gained from betting through the Service whilst under age must be paid to us on demand (if you fail to comply with this provision we will seek to recover all costs associated with recovery of such sums); and/or</li>
              <li>any monies deposited in your Account which are not winnings will be returned to you OR retained until you turn 18 years old at our sole discretion. We reserve the right to deduct payment transaction fees from the amount to return, including transaction fees for deposits to your alpacasino.io account which we covered.</li>
            </ul>
            16.2. This condition also applies to you if you are over the age of 18 years but you are placing your bets within a jurisdiction which specifies a higher age than 18 years for legal betting and you are below that legal minimum age in that jurisdiction.<br />
            16.3. In the event we suspect you are in breach of the provisions of this Clause or are attempting to rely on them for a fraudulent purpose, we reserve the right to take any action necessary in order to investigate the matter, including informing the relevant law enforcement agencies.
          </p>

          <h2>17. Fraud</h2>
          <p>
            We will seek criminal and contractual sanctions against any Customer involved in fraud, dishonesty or criminal acts. We will withhold payment to any Customer where any of these are suspected. The Customer shall indemnify and shall be liable to pay to us on demand all costs, charges or losses sustained or incurred by us (including any direct, indirect or consequential losses, loss of profit, loss of business and loss of reputation) arising directly or indirectly from the Customer’s fraud, dishonesty or criminal act.
          </p>

          <h2>18. Intellectual Property</h2>
          <p>
            18.1. Any unauthorised use of our name and logo may result in legal action being taken against you.<br />
            18.2. As between us and you, we are the sole owners of the rights in and to the Service, our technology, software and business systems (the "Systems") as well as our odds.you must not use your personal profile for your own commercial gain (such as selling your status update to an advertiser); andwhen selecting a nickname for your Account we reserve the right to remove or reclaim it if we believe it appropriate.<br />
            18.3. You may not use our URL, trademarks, trade names and/or trade dress, logos ("Marks") and/or our odds in connection with any product or service that is not ours, that in any manner is likely to cause confusion among Customers or in the public or that in any manner disparages us.<br />
            18.4. Except as expressly provided in these Terms, we and our licensors do not grant you any express or implied rights, license, title or interest in or to the Systems or the Marks and all such rights, license, title and interest specifically retained by us and our licensors. You agree not to use any automatic or manual device to monitor or copy web pages or content within the Service. Any unauthorized use or reproduction may result in legal action being taken against you.
          </p>

          <h2>19. Your License</h2>
          <p>
            19.1. Subject to these Terms and your compliance with them, we grant to you a non-exclusive, limited, non transferable and non sub-licensable license to access and use the Service for your personal non-commercial purposes only. Our license to you terminates if our agreement with you under these Terms ends.<br />
            19.2. Save in respect of your own content, you may not under any circumstances modify, publish, transmit, transfer, sell, reproduce, upload, post, distribute, perform, display, create derivative works from, or in any other manner exploit, the Service and/or any of the content thereon or the software contained therein, except as we expressly permit in these Terms or otherwise on the Website. No information or content on the Service or made available to you in connection with the Service may be modified or altered, merged with other data or published in any form including for example screen or database scraping and any other activity intended to collect, store, reorganise or manipulate such information or content.<br />
            19.3. Any non-compliance by you with this Clause may also be a violation of our or third parties' intellectual property and other proprietary rights which may subject you to civil liability and/or criminal prosecution.
          </p>

          <h2>20. Your Conduct and Safety</h2>
          <p>
            20.1. For your protection and protection of all our Customers, the posting of any content on the Service, as well as conduct in connection therewith and/or the Service, which is in any way unlawful, inappropriate or undesirable is strictly prohibited (“Prohibited Behaviour”).<br />
            20.2. If you engage in Prohibited Behaviour, or we determine in our sole discretion that you are engaging in Prohibited Behaviour, your Account and/or your access to or use of the Service may be terminated immediately without notice to you. Legal action may be taken against you by another Customer, other third party, enforcement authorities and/or us with respect to you having engaged in Prohibited Behaviour.<br />
            20.3. Prohibited Behaviour includes, but is not limited to, accessing or using the Service to: <br />
            promote or share information that you know is false, misleading or unlawful;<br />
            conduct any unlawful or illegal activity, such as, but not limited to, any activity that furthers or promotes any criminal activity or enterprise, violates another Customer's or any other third party’s privacy or other rights or that creates or spreads computer viruses;<br />
            harm minors in any way;transmit or make available any content that is unlawful, harmful, threatening, abusive, tortuous, defamatory, vulgar, obscene, lewd, violent, hateful, or racially or ethnically or otherwise objectionable;<br />
            transmit or make available any content that the user does not have a right to make available under any law or contractual or fiduciary relationship, including without limitation, any content that infringes a third party’s copyright, trademark or other intellectual property and proprietary rights;<br />
            transmit or make available any content or material that contains any software virus or other computer or programming code (including HTML) designed to interrupt, destroy or alter the functionality of the Service, its presentation or any other website, computer software or hardware;<br />
            interfere with, disrupt or reverse engineer the Service in any manner, including, without limitation, intercepting, emulating or redirecting the communication protocols used by us, creating or using cheats, mods or hacks or any other software designed to modify the Service, or using any software that intercepts or collects information from or through the Service;retrieve or index any information from the Service using any robot, spider or other automated mechanism;<br />
            participate in any activity or action that, in the sole and entire unfettered discretion of us results or may result in another Customer being defrauded or scammed;<br />
            transmit or make available any unsolicited or unauthorised advertising or mass mailing such as, but not limited to, junk mail, instant messaging, "spim", "spam", chain letters, pyramid schemes or other forms of solicitations;<br />
            create Accounts on the Website by automated means or under false or fraudulent pretences;<br />
            impersonate another Customer or any other third party, orany other act or thing done that we reasonably consider to be contrary to our business principles.<br />
            The above list of Prohibited Behaviour is not exhaustive and may be modified by us at any time or from time to time. We reserve the right to investigate and to take all such actions as we in our sole discretion deem appropriate or necessary under the circumstances, including without limitation deleting the Customer’s posting(s) from the Service and/or terminating their Account, and take any action against any Customer or third party who directly or indirectly in, or knowingly permits any third party to directly or indirectly engage in Prohibited Behaviour, with or without notice to such Customer or third party.
          </p>

          <h2>21. Links to Other Websites</h2>
          <p>The Service may contain links to third party websites that are not maintained by, or related to, us, and over which we have no control. Links to such websites are provided solely as a convenience to Customers, and are in no way investigated, monitored or checked for accuracy or completeness by us. Links to such websites do not imply any endorsement by us of, and/or any affiliation with, the linked websites or their content or their owner(s). We have no control over or responsibility for the availability nor their accuracy, completeness, accessibility and usefulness. Accordingly when accessing such websites we recommend that you should take the usual precautions when visiting a new website including reviewing their privacy policy and terms of use.</p>

          <h2>22. Complaints</h2>
          <p>
            22.1. If you have any concerns or questions regarding these Terms you should contact our Customer Service Department via the links on the Website and use your Registered Email Address in all communication with us.<br />
            22.2. NOTWITHSTANDING THE FOREGOING, WE TAKE NO LIABILITY WHATSOEVER TO YOU OR TO ANY THIRD PARTY WHEN RESPONDING TO ANY COMPLAINT THAT WE RECEIVED OR TOOK ACTION IN CONNECTION THEREWITH.<br />
            22.3. If a Customer is not satisfied with how a bet has been settled then the Customer should provide details of their grievance to our Customer Service Department. We shall use our reasonable endeavours to respond to queries of this nature within a few days (and in any event we intend to respond to all such queries within 28 days of receipt).<br />
            22.4. Disputes must be lodged within three (3) days from the date the wager in question has been decided. No claims will be honoured after this period. The Customer is solely responsible for their Account transactions.<br />
            22.5. In the event of a dispute arising between you and us our Customer Service Department will attempt to reach an agreed solution. Should our Customer Service Department be unable to reach an agreed solution with you, the matter will be escalated to our management.<br />
            22.6. Should all efforts to resolve a dispute to the Customer's satisfaction have failed, the Customer has the right to lodge a complaint with our licensing body Gaming Services Provider N.V.
          </p>

          <h2>23. Assignment</h2>
          <p>Neither these Terms nor any of the rights or obligations hereunder may be assigned by you without the prior written consent of us, which consent will not be unreasonably withheld. We may, without your consent, assign all or any portion of our rights and obligations hereunder to any third party provided such third party is able to provide a service of substantially similar quality to the Service by posting written notice to this effect on the Service.</p>

          <h2>24. Severability</h2>
          <p>In the event that any provision of these Terms is deemed by any competent authority to be unenforceable or invalid, the relevant provision shall be modified to allow it to be enforced in line with the intention of the original text to the fullest extent permitted by applicable law. The validity and enforceability of the remaining provisions of these Terms shall not be affected.</p>

          <h2>25. Breach of These Terms</h2>
          <p>Without limiting our other remedies, we may suspend or terminate your Account and refuse to continue to provide you with the Service, in either case without giving you prior notice, if, in our reasonable opinion, you breach any material term of these Terms. Notice of any such action taken will, however, be promptly provided to you.</p>

          <h2>26. General Provisions</h2>
          <p>
            26.1. <b>Term of agreement</b>. These Terms shall remain in full force and effect while you access or use the Service or are a Customer or visitor of the Website. These Terms will survive the termination of your Account for any reason.<br />
            26.2. <b>Gender</b>. Words importing the singular number shall include the plural and vice versa, words importing the masculine gender shall include the feminine and neuter genders and vice versa and words importing persons shall include individuals, partnerships, associations, trusts, unincorporated organisations and corporations.<br />
            26.3. <b>Waiver</b>. No waiver by us, whether by conduct or otherwise, of a breach or threatened breach by you of any term or condition of these Terms shall be effective against, or binding upon, us unless made in writing and duly signed by us, and, unless otherwise provided in the written waiver, shall be limited to the specific breach waived. The failure of us to enforce at any time any term or condition of these Terms shall not be construed to be a waiver of such provision or of the right of us to enforce such provision at any other time.<br />
            26.4. <b>Acknowledgement</b>. By hereafter accessing or using the Service, you acknowledge having read, understood and agreed to each and every paragraph of these Terms. As a result, you hereby irrevocably waive any future argument, claim, demand or proceeding to the contrary of anything contained in these Terms.<br />
            26.5. <b>Language</b>. In the event of there being a discrepancy between the English language version of these rules and any other language version, the English language version will be deemed to be correct.<br />
            26.6. <b>Governing Law</b>. These Terms are governed by the law in force in Curaçao.<br />
            26.7. <b>Entire agreement</b>. These Terms constitute the entire agreement between you and us with respect to your access to and use of the Service, and supersedes all other prior agreements and communications, whether oral or written with respect to the subject matter hereof.
          </p>
      </div>
        
      </div>
    </BaseContainerWithNavbar>
  );
};

export default TermsConditions;
