export default {
  auth: 'auth',
  betApprove: 'betApprove',
  betView: 'betView',
  eventDetails: 'eventDetails',
  referralList: 'referralList',
  tradeDetails: 'tradeDetails',
  welcome: 'welcome',
  signUpNotificationFirst: 'signUpNotificationFirst',
  signUpNotificationSecond: 'signUpNotificationSecond',
  tradeView: 'tradeView',
  withdrawalSuccess: 'withdrawalSuccess',
  deposit: 'deposit',
  evaluateEvent: 'evaluateEvent',
  reportEvent: 'reportEvent',
  loginRegister: 'loginRegister',
  verifyEmail: 'verifyEmail',
  pulloutApprove: 'pulloutApprove',
  lotteryGameAnswered: 'lotteryGameAnswered',
  newEvent: 'newEvent',
  editEvent: 'editEvent',
  newBet: 'newBet',
  editBet: 'editBet',
  viewImage: 'viewImage',
  resolveBet: 'resolveBet',
  share: 'share',
};
