export default [
  `Notification/EVENT_USER_SIGNED_UP`,
  'Notification/EVENT_USER_REWARD',
  'Notification/EVENT_USER_UPLOADED_PICTURE',
  'Notification/EVENT_USER_CHANGED_USERNAME',
  'Notification/EVENT_USER_CHANGED_NAME',
  'Notification/EVENT_USER_CHANGED_ABOUT_ME',
  'Notification/EVENT_ONLINE',
  'Notification/EVENT_OFFLINE',
  'Notification/EVENT_NEW',
  'Notification/EVENT_NEW_BET ',
  'Notification/EVENT_BET_PLACED',
  'Notification/EVENT_BET_CASHED_OUT',
  'Notification/EVENT_BET_RESOLVED',
  'Notification/EVENT_BET_CANCELED',
  'Notification/EVENT_BET_EVALUATED',
  'Casino/CASINO_PLACE_BET',
  'Casino/CASINO_CASHOUT',
  'Casino/EVENT_CASINO_LOST',
  'Notification/EVENT_USER_KYC_UPDATE',
];
